# Generated by Django 6.1.1 on 2026-10-06 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_hardcoded_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to='originals/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=8)),
                ('failure_reason', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='material.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('markdown', models.TextField()),
                ('plain_text', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='material.sourcefile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='material.slide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('source_file', 'number'), name='unique_slide_number_per_file'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.UniqueConstraint(fields=('slide', 'ordinal'), name='unique_span_ordinal_per_slide'),
        ),
    ]
