# Generated by Django 6.1.1 on 2026-10-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='failure_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='stages',
            field=models.JSONField(default=list),
        ),
    ]
