# Generated by Django 6.1.2 on 2026-10-09 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_sourcefile_failure_advice_sourcefile_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_note', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='material.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Awaiting confirmation'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_path', to='material.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_pointers', to='material.slide')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointers', to='material.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_slides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slide__source_file_id', 'slide__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='unique_topic_position_per_course'),
        ),
        migrations.AddConstraint(
            model_name='topicslide',
            constraint=models.UniqueConstraint(fields=('topic', 'slide'), name='unique_slide_per_topic'),
        ),
    ]
