# Generated by Django 6.1.1 on 2026-10-10 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_plan_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='skipped_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('passes', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='material.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['taken_at', 'id'],
            },
        ),
    ]
