# Generated by Django 6.1.1 on 2026-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_topic_completed_on_topic_skipped_on_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cut_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
