# Generated by Django 6.1.1 on 2026-10-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_topic_cut_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped', models.PositiveIntegerField(default=0)),
                ('low_confidence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='material.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('short_answer', 'Short answer')], max_length=16)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='material.span')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='material.quiz')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'ordinal'), name='unique_question_ordinal_per_quiz')],
            },
        ),
    ]
