# Generated by Django 6.1.1 on 2026-10-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_quiz_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptMissed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_rows', to='material.attempt')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_in', to='material.span')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_misseds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['span_id'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='missed',
            field=models.ManyToManyField(related_name='missed_attempts', through='material.AttemptMissed', to='material.span'),
        ),
        migrations.CreateModel(
            name='SectionOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='material.span')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['opened_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='attemptmissed',
            constraint=models.UniqueConstraint(fields=('attempt', 'span'), name='unique_missed_span_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='sectionopen',
            constraint=models.UniqueConstraint(fields=('user', 'span'), name='unique_open_per_span'),
        ),
    ]
